name: build

on: [push]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v -ldflags="-s -w" cmd/extraterm-launcher/extraterm-launcher.go

    - name: Test
      run: go test -v ./...

    - name: Keep the executable
      uses: actions/upload-artifact@v2
      with:
        name: extraterm-launcher-linux
        path: extraterm-launcher

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v -ldflags="-s -w" cmd/extraterm-launcher/extraterm-launcher.go

    - name: Test
      run: go test -v ./...

    - name: Keep the executable
      uses: actions/upload-artifact@v2
      with:
        name: extraterm-launcher-macos
        path: extraterm-launcher

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Download rcedit.exe
      shell: pwsh
      run: Invoke-WebRequest -Uri https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe -OutFile rcedit.exe

    - name: Build
      run: go build -v -ldflags "-s -w -H=windowsgui" cmd/extraterm-launcher/extraterm-launcher.go

    - name: Test
      run: go test -v ./...

    - name: Insert icon on exe
      run: .\rcedit.exe extraterm-launcher.exe --set-icon resources/extraterm_small_logo.ico

    - name: Keep the executable
      uses: actions/upload-artifact@v2
      with:
        name: extraterm-launcher-windows
        path: extraterm-launcher.exe

  release-tag-as-draft:
    name: Release tag as a draft release
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download Linux executable
      uses: actions/download-artifact@v2
      with:
        name: extraterm-launcher-linux
        path: extraterm-launcher-linux

    - name: Download MacOS executable
      uses: actions/download-artifact@v2
      with:
        name: extraterm-launcher-macos
        path: extraterm-launcher-macos

    - name: Download Windows executable
      uses: actions/download-artifact@v2
      with:
        name: extraterm-launcher-windows
        path: extraterm-launcher-windows

    - name: Create GH release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          extraterm-launcher-linux
          extraterm-launcher-macos
          extraterm-launcher-windows
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
